<?php
$metaData = '{';
$metaData .= "'ajaxUrl':'" . ('/modules/vaf/process.php') . "',";
$metaData .= "'quickAddUrl':'" . ('*/definitions/save') . "',";
$metaData .= "'elementName':'vaf'";
$metaData .= ", 'initialSelections':[{'level':'3','id':'0','node':{},'path':['','','']}]";
$metaData .= "}";
?>

<div class="multiTree <?= $metaData ?>">
    <?php
    $schema = new VF_Schema();
    $levels = $schema->getLevels();
    foreach ($levels as $level) {
        ?>
        <div class="multiTree-selectContainer">
            <?=ucfirst(htmlentities($level))?>:<br/>
            <?php
            $metadata = "{level:'$level', parent:'" . $schema->getPrevLevel($level) . "', parents:'" . implode(
                ',',
                $schema->getPrevLevels($level)
            ) . "',  parents_including:'" . implode(',', $schema->getPrevLevelsIncluding($level)) . "' }";
            ?>
            <select class="multiTree-select <?= $level ?>Select <?= $metadata ?>" size="10">
                <?php
                if ($schema->getRootLevel() == $level) {
                    $entity = new VF_Level($schema->getRootLevel());
                    foreach ($entity->listAll() as $item) {
                        ?>
                        <option value="<?= $item->getId() ?>"><?=$item->getTitle()?></option>
                    <?php
                    }
                }
                ?>
            </select>
            <br/>
            Quick Add:
            <br/>
            <input type="text" class="vafQuickAdd vafQuickAdd_<?= $level ?> {level:'<?= $level ?>'}"
                   name="vafQuickAdd_<?= $level ?>"/>
            <input type="button" class="vafQuickAddSubmit vafQuickAddSubmit_<?= $level ?> {level:'<?= $level ?>'}"
                   name="vafQuickAddSubmit_<?= $level ?>" value="+"/>
            <br/>
            <span class="multiTree-levelName" style="display:none;"><?=$level?></span>
        </div>
    <?php
    }
    ?>
    <input class="multiTree-Add" type="button" value="Add +"/>
    <br clear="all"/>
    <input type="checkbox" class="vafCheckAll"/> Select All
    <br/>
    <a href="#" class="vafDeleteSelected">Delete Selected</a>

    <div class="multiTree-selections" style="height:500px; overflow:auto;">
        <?php
        foreach (Elite_Vaf_Helper_Data::getInstance()->getFits($_GET['id_product']) as $fit) {
            $leafLevel = $schema->getLeafLevel();
            ?>
            <div class="multiTree-selection">
                <input type="checkbox" name="vafcheck[]" class="vafcheck" value="<?= $leafLevel ?>-<?= $fit->id ?>"/>

                <div class="multiTree-value" style="display:none"><?=$leafLevel?>-<?=$fit->id?></div>
                <a class="multiTree-closeLink" href="#">[ x ]</a>
                <?php
                $label = array();
                $schema = new VF_Schema();
                foreach ($schema->getLevels() as $level) {
                    $label[] = htmlentities($fit->$level);
                }
                echo implode('<span class="multiTree-selection-seperator">&raquo;</span>', $label);
                ?>

            </div>
        <?php
        }
        ?>
    </div>
    <div class="multiTree-new-selections"></div>
    <div class="multiTree-deleted-selections"></div>

    <!-- start VAF -->
    <script src="/modules/vaf/jquery.metadata.pack.js" type="text/javascript" language="javascript"></script>
    <script src="/modules/vaf/js.php" type="text/javascript" language="javascript"></script>
    <link rel="stylesheet" type="text/css" href="/modules/vaf/multiTree.css"/>
    <!-- end VAF -->